import { type NextPage } from "next";
import Head from "next/head";
import HomeNav from "~/components/HomeNav";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const {data} = api.groups.getAll.useQuery();

  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeNav  />
    </>
  );
};

export default Home;
